version: "1.0"
project:
  metadata:
    projectName: "demo-node-service"
    businessUnit: "PlatformEngineering"
    team: "core-devops"
    repositoryUrl: "http://buildos-git:3000/aadu/demo-node-service.git"
    scmCredentialsId: "git"
    description: "Node.js Express Microservice Target"
  version: "1.0.0-SNAPSHOT"

nexus:
  url: "http://buildos-nexus:8081"
  credentialsId: "enterprise-nexus-credentials"

branchGovernance:
  includePatterns:
    - "^main$"
    - "^feature/.*"

rbac:
  folderAuth:
    useFolderBasedAuth: true
    admins: ["aadu"]

quality:
  coverage:
    tool: "cobertura"
    lineCoverageThreshold: 80
  sonarQube:
    hostUrl: "http://buildos-sonarqube:9000"

observability:
  audit:
    enabled: true
    logLevel: "INFO"
